name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2 # Atualizado para a última versão disponível

    - name: Set up Python
      uses: actions/setup-python@v2 # Atualizado para a última versão disponível
      with:
        python-version: '3.8'

    - name: Create Virtual Environment
      run: python -m venv venv

    - name: Copy resources folder
      run: cp -r../resources./resources

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest selenium pytest-html
        
    - name: Esteira de testes e Generate Reports
      run: |
        pytest -v --html=report.html  \
                --self-contained-html \
                --capture=sys \
                --verbose \
                --showlocals \
                --durations=0 

    - name: Upload HTML Report
      uses: actions/upload-artifact@v4 # Atualizado para a versão 4
      if: always()
      with:
        name: TestReportsSE-Exemplo_html
        path: report.html
    