name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      # Usa a ação checkout para obter o código do repositório. Esta é uma boa prática padrão.

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
      # Configura o Python 3.8, que é a versão especificada. É importante manter a versão do Python consistente com o ambiente de desenvolvimento.

    - name: Create Virtual Environment
      run: python -m venv venv
      # Cria um ambiente virtual para instalar as dependências isoladamente. Isso é uma boa prática para evitar conflitos de dependências.

    - name: Activate Virtual Environment
      run: source $HOME/venv/bin/activate
      shell: bash
      # Ativa o ambiente virtual criado. Note que esta etapa é necessária para usar o ambiente virtual nas etapas subsequentes.

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      # Atualiza o pip e instala as dependências listadas no requirements.txt. É importante garantir que este arquivo esteja atualizado.

    - name: Execute Tests and Generate Reports
      run: |
        pytest -v --html=report.html \
                --self-contained-html \
                --capture=sys \
                --verbose \
                --showlocals \
                --durations=0
      # Executa os testes com pytest e gera um relatório HTML. Os backslashes (\) foram removidos para melhor legibilidade.

    - name: Upload HTML Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: TestReport
        path: report.html
      # Faz upload do relatório HTML como um artefato, independentemente do resultado dos testes. Isso é útil para análises pós-execução.

    - name: Deactivate Virtual Environment
      run: deactivate
      shell: bash
      # Desativa o ambiente virtual após a conclusão dos testes, embora não estritamente necessário, é uma boa prática de limpeza.
